In [1]:
class ABC:
    a: int 
    b: int 
    

In [7]:
a = ABC()
a.a = "aaaaa"
print(a.a)

aaaaa


In [3]:
import numpy as np
import numpy as np

# 创建一个三维数组
a = np.ones((5, 1))
arr = np.broadcast_to(a, (5, 4))
print(arr)
# 沿着指定的多个轴进行求和
# sum_axes = np.sum(arr, axis=tuple([1]))
# print("Sum along axes (0, 2):", sum_axes)
# np.transpose(a, axes=(0, 1, 2)).shape

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
a = (3, 2, 3)
b = (3,)
a[:2]

(3, 2)